# Generated by Django 4.1.3 on 2022-12-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('points', models.IntegerField(max_length=10)),
                ('rank', models.IntegerField(max_length=10)),
                ('country', models.CharField(max_length=128)),
                ('coach', models.CharField(max_length=128)),
                ('history', models.FileField(blank=True, null=True, upload_to='hltv_histories/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hltv_teams/')),
                ('inst', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=128)),
                ('last', models.CharField(max_length=128)),
                ('age', models.IntegerField(max_length=10)),
                ('country', models.CharField(max_length=128)),
                ('rating', models.FloatField(max_length=10)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='hltv_teams/')),
                ('nickname', models.CharField(max_length=64)),
                ('inst', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('twitch', models.CharField(blank=True, max_length=100, null=True)),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='hltv.team')),
            ],
        ),
    ]
