# Generated by Django 4.1.3 on 2022-12-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hltv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='history',
            new_name='trophies',
        ),
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
