# Generated by Django 4.1.3 on 2022-12-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hltv', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('prize_pool', models.IntegerField(default=150000)),
                ('country', models.CharField(max_length=128)),
            ],
        ),
    ]
