# Generated by Django 4.1.3 on 2022-12-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hltv', '0005_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hltv_teams/'),
        ),
    ]
