# Generated by Django 4.1.3 on 2022-12-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hltv', '0007_podcast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
