# Generated by Django 4.1.3 on 2022-12-16 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hltv', '0011_matchcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchcomment',
            options={'ordering': ['-published']},
        ),
        migrations.AddField(
            model_name='team',
            name='fans',
            field=models.ManyToManyField(blank=True, null=True, related_name='favs', to=settings.AUTH_USER_MODEL),
        ),
    ]
