# Generated by Django 4.1.3 on 2022-12-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hltv', '0012_alter_matchcomment_options_team_fans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='portrait',
            new_name='logo',
        ),
    ]
