# Generated by Django 4.1.3 on 2022-12-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hltv', '0014_alter_team_fans'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='maps_played',
            field=models.IntegerField(default=50),
        ),
    ]
