# Generated by Django 4.1.3 on 2022-12-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hltv', '0015_player_maps_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='major_ach',
            field=models.FileField(blank=True, null=True, upload_to='player_ach/'),
        ),
    ]
